name: Java CI Test Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set env variable dl
        run: setx /m PATH "%cd%;%PATH%"
      - name: Run DL
        run: youtube-dl -f bestaudio https://www.youtube.com/watch?v=QK8mJJJvaes
        shell: cmd
      - name: Run project
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: mvn -e -B package --file pom.xml
        shell: cmd